# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 108d37b0accd416ded8809016851fd277235bf9e2784b7dc102a5bf9d102aa0537a125f934854d0e62e314ab2ff316f3b5acc3d5ac474ef2256bfdeb7f7d086e

test:
  secret_key_base: 29f44d74eda8048f1ac0bc44e650234913dad1d65e4171f92b8ccc759d39ed0b249adf873723e70d2e311b2c741a51310a048b4a933ea4ff7fa7cb4803531cc9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
